### ISSUE TITLE
Pressing F3 (reload) results in an error below

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#137]
And not only F3, but any reload.
----------------------------------------
----------------------------------------
----------------------------------------

2024-04-17 14:01:02,976 - api.bybit.ws - INFO - Websocket closed
++++ Bybit -1
_____ ('BTCUSDT', 'linear', 'Bybit') 0
-----starting Bybit----
2024-04-17 14:01:03,937 - api.bybit.ws - INFO - Connecting to websocket
2024-04-17 14:01:03,937 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-04-17 14:01:04,843 - websocket - INFO - Websocket connected
2024-04-17 14:01:04,844 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
_________ws subscription: linear - orderbook_stream - ('BTCUSDT', 'linear', 'Bybit')
_________ws subscription: linear - ticker_stream - ('BTCUSDT', 'linear', 'Bybit')
2024-04-17 14:01:04,845 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-04-17 14:01:05,842 - websocket - INFO - Websocket connected
2024-04-17 14:01:05,843 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) connected
___get_user
___wallet_balance
___get_position_info
___trading_history
Bybit - loading trading history, startTime=2024-04-17 08:14:42, received: 1 records.
___trading_history
Bybit - loading trading history, startTime=2024-04-17 08:14:42.148000, received: 1 records.
___trading_history
Bybit - loading trading history, startTime=2024-04-17 08:14:42.148000, received: 1 records.
___open_orders
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/tmatic_240417_2/connect.py", line 22, in <lambda>
    disp.root.bind("<F3>", lambda event: terminal_reload(event))
  File "/home/tmatic_240417_2/connect.py", line 139, in terminal_reload
    setup()
  File "/home/tmatic_240417_2/connect.py", line 30, in setup
    setup_market(Markets[name])
  File "/home/tmatic_240417_2/connect.py", line 66, in setup_market
    ws.robots[emi]["STATUS"] = value
KeyError: 'XBTUSDT.linear'

**Comment by evgrmn** [comment]
The robot_status variable was declared incorrectly. Tested close() functions for websockets.
