### ISSUE TITLE
An error while switching to Bybit exchange

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#176]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/tmatic_240424/main.py", line 16, in refresh
    connect.refresh()
  File "/home/rmn/tmatic_240424/connect.py", line 114, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/home/rmn/tmatic_240424/functions.py", line 704, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/tmatic_240424/functions.py", line 990, in refresh_tables
    update_label(table="account", column=0, row=num + mod, val=settlCurrency[0])
  File "/home/rmn/tmatic_240424/functions.py", line 1584, in update_label
    if disp.labels_cache[table][row][column] != val:
IndexError: list index out of range

**Comment by evgrmn** [comment]
Corrected row number for Account table In clear_tables() function.
