### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#191]
At the first loading after initial transaction history. The second loading showed no errors.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/Users/nrmn/Documents/tmatic_240424/main.py", line 16, in refresh
    connect.refresh()
  File "/Users/nrmn/Documents/tmatic_240424/connect.py", line 109, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/Users/nrmn/Documents/tmatic_240424/functions.py", line 704, in refresh_on_screen
    Function.refresh_tables(self)
  File "/Users/nrmn/Documents/tmatic_240424/functions.py", line 1215, in refresh_tables
    update_label(table="results", column=0, row=num + mod, val=currency[0])
  File "/Users/nrmn/Documents/tmatic_240424/functions.py", line 1760, in update_label
    if disp.labels_cache[table][row][column] != val:
       ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
IndexError: list index out of range

**Comment by evgrmn** [comment]
A trade with a specific currency was found in the trading history, but that currency was not assigned in the .env file. It was agreed:
1. All traded currencies are checked in the database and added to the list of currencies.
2. All currencies are added in advance from subscribed symbols.
