### ISSUE TITLE
Sleep mode, then F3 reboot leads to error. Tmatic's running but some widgets are not visible

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#240]
![Screenshot from 2024-06-06 15-49-46](https://github.com/evgrmn/tmatic/assets/148801289/7dfbeb74-5846-4df6-b266-cf53a75fdbe9)

2024-06-06 12:37:33,278 - functions - INFO - Emboldening SQLite
2024-06-06 12:37:35,420 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-06-06 12:37:36,190 - websocket - INFO - Websocket connected
2024-06-06 12:37:36,191 - api.bybit.pybit._websocket_stream - ERROR - WebSocket Unified V5 (wss://stream-testnet.bybit.com/v5/public/linear) encountered error: Connection to remote host was lost..
2024-06-06 12:37:36,191 - api.bybit.pybit._websocket_stream - ERROR - WebSocket Unified V5 (Auth) (wss://stream-testnet.bybit.com/v5/private) encountered error: Connection to remote host was lost..
2024-06-06 12:37:36,192 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-06-06 12:37:36,192 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-06-06 12:37:36,193 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-06-06 12:37:36,245 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-06-06 12:37:36,926 - websocket - INFO - Websocket connected
2024-06-06 12:37:36,942 - websocket - INFO - Websocket connected
2024-06-06 12:37:36,929 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) connected
2024-06-06 12:37:36,946 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-06-06 12:37:36,946 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-06-06 12:37:36,947 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-06-06 12:37:37,178 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x7ec661c53640>: Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3fi5daugt7mgdqvtg-2x4n1'}
2024-06-06 12:37:37,402 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x7ec661cac1f0>: Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3fi5daugt7mgdqvtg-2x4n1'}
2024-06-06 12:37:37,402 - websocket - INFO - tearing down on exception Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3fi5daugt7mgdqvtg-2x4n1'}
2024-06-06 12:37:40,409 - api.bybit.pybit._websocket_stream - ERROR - WebSocket Unified V5 (wss://stream-testnet.bybit.com/v5/public/linear) encountered error: ping/pong timed out.
2024-06-06 12:37:40,420 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-06-06 12:37:41,159 - websocket - INFO - Websocket connected
2024-06-06 12:37:41,163 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-06-06 12:37:41,169 - websocket - ERROR - ping/pong timed out - goodbye
2024-06-06 12:37:43,472 - api.bitmex.ws - ERROR - Error: Connection to remote host was lost.
2024-06-06 12:37:43,472 - websocket - ERROR - Connection to remote host was lost. - goodbye
2024-06-06 12:37:43,472 - api.bitmex.ws - INFO - Bitmex - Websocket closed
2024-06-06 12:37:43,672 - api.bitmex.http - INFO - (https) sending GET to instrument/active: ""
2024-06-06 12:37:43,975 - api.bitmex.http - INFO - (https) sending GET to order?filter=%7B%22open%22%3A%20true%7D&reverse=false: ""
2024-06-06 12:37:44,055 - api.bitmex.ws - INFO - Connecting to websocket
2024-06-06 12:37:44,055 - api.bitmex.http - INFO - (https) sending GET to user: ""
2024-06-06 12:37:44,058 - api.bitmex.ws - INFO - Authenticating with API key.
2024-06-06 12:37:44,059 - api.bitmex.http - INFO - (https) sending GET to position: ""
2024-06-06 12:37:44,343 - websocket - INFO - Websocket connected
2024-06-06 12:37:45,064 - api.bitmex.ws - INFO - Connected to websocket.
2024-06-06 12:37:45,265 - api.bitmex.ws - INFO - Data received. Continuing.
2024-06-06 12:37:45,300 - api.bitmex.http - INFO - (https) sending GET to execution/tradeHistory?count=500&reverse=false&startTime=2024-06-05 07:42:12: ""
2024-06-06 12:37:45,646 - common.init - INFO - Robot EMI=XbtInv1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:37:45,650 - common.init - INFO - Robot EMI=Xbt1_1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:37:45,651 - common.init - INFO - Robot EMI=Xbt5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:37:45,651 - common.init - INFO - Robot EMI=Xbt1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:37:45,651 - common.init - INFO - Robot EMI=XbtInv5. Adding to 'robots' with STATUS='NOT DEFINED'
______Tmatic: Bybit API is still pinging, but the websocket is already closed
2024-06-06 12:45:00,167 - functions - INFO - Posting symbol=('BTCUSDT', 'linear', 'Bybit') clOrdID=1264836826.BTCUSDT.linear side=Sell price=91253.6 qty=-0.001
2024-06-06 12:45:19,114 - api.bybit.ws - INFO - Bybit - Websocket closed
2024-06-06 12:45:19,166 - api.bitmex.ws - INFO - Bitmex - Websocket closed
2024-06-06 12:45:19,182 - api.bitmex.http - INFO - (https) sending GET to instrument/active: ""
2024-06-06 12:45:19,444 - api.bitmex.http - INFO - (https) sending GET to order?filter=%7B%22open%22%3A%20true%7D&reverse=false: ""
2024-06-06 12:45:19,543 - api.bitmex.ws - INFO - Connecting to websocket
2024-06-06 12:45:19,544 - api.bitmex.ws - INFO - Authenticating with API key.
2024-06-06 12:45:19,544 - api.bitmex.http - INFO - (https) sending GET to user: ""
2024-06-06 12:45:19,550 - api.bitmex.http - INFO - (https) sending GET to position: ""
2024-06-06 12:45:19,786 - websocket - INFO - Websocket connected
2024-06-06 12:45:20,551 - api.bitmex.ws - INFO - Connected to websocket.
2024-06-06 12:45:21,052 - api.bitmex.ws - INFO - Data received. Continuing.
2024-06-06 12:45:21,098 - api.bitmex.http - INFO - (https) sending GET to execution/tradeHistory?count=500&reverse=false&startTime=2024-06-05 07:42:12: ""
2024-06-06 12:45:21,473 - common.init - INFO - Robot EMI=XbtInv1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:21,473 - common.init - INFO - Robot EMI=Xbt1_1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:21,473 - common.init - INFO - Robot EMI=Xbt5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:21,473 - common.init - INFO - Robot EMI=Xbt1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:21,474 - common.init - INFO - Robot EMI=XbtInv5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:21,502 - api.bybit.ws - INFO - Bybit - Websocket closed
2024-06-06 12:45:21,503 - api.bybit.agent - INFO - Sending get_instruments_info() - category - spot
2024-06-06 12:45:21,505 - api.bybit.agent - INFO - Sending get_instruments_info() - category - inverse
2024-06-06 12:45:21,508 - api.bybit.agent - INFO - Sending get_instruments_info() - category - option
2024-06-06 12:45:21,510 - api.bybit.agent - INFO - Sending get_instruments_info() - category - linear
2024-06-06 12:45:21,550 - api.bitmex.http - INFO - (https) sending GET to instrument/active: ""
2024-06-06 12:45:21,693 - api.bitmex.http - INFO - (https) sending GET to order?filter=%7B%22open%22%3A%20true%7D&reverse=false: ""
2024-06-06 12:45:21,776 - api.bitmex.ws - INFO - Connecting to websocket
2024-06-06 12:45:21,776 - api.bitmex.ws - INFO - Authenticating with API key.
2024-06-06 12:45:21,777 - api.bitmex.http - INFO - (https) sending GET to user: ""
2024-06-06 12:45:21,779 - api.bitmex.http - INFO - (https) sending GET to position: ""
2024-06-06 12:45:22,060 - websocket - INFO - Websocket connected
2024-06-06 12:45:22,159 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'spot', 'cursor': 'no'}
2024-06-06 12:45:22,160 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'linear', 'settleCoin': 'USDT', 'cursor': 'no'}
2024-06-06 12:45:22,779 - api.bitmex.ws - INFO - Connected to websocket.
2024-06-06 12:45:22,803 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'linear', 'settleCoin': 'USDT', 'cursor': 'c645fc0a-8892-4ed6-8a51-c3a4b61bab19%3A1717677901890%2Caa2205dd-6474-4199-9540-67c7e709a1d7%3A1716477047327'}
2024-06-06 12:45:22,980 - api.bitmex.ws - INFO - Data received. Continuing.
2024-06-06 12:45:23,019 - api.bitmex.http - INFO - (https) sending GET to execution/tradeHistory?count=500&reverse=false&startTime=2024-06-05 07:42:12: ""
2024-06-06 12:45:23,467 - api.bybit.ws - INFO - Connecting to websocket
2024-06-06 12:45:23,467 - api.bybit.agent - INFO - Sending get_uid_wallet_type()
2024-06-06 12:45:23,468 - api.bybit.agent - INFO - Sending get_wallet_balance() - accountType - UNIFIED
2024-06-06 12:45:23,470 - api.bybit.agent - INFO - Sending get_positions() - category - linear - settlCurrency - USDT
2024-06-06 12:45:23,473 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-06-06 12:45:23,473 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-06-06 12:45:23,883 - api.bybit.agent - INFO - Sending get_wallet_balance() - accountType - CONTRACT
2024-06-06 12:45:25,407 - websocket - INFO - Websocket connected
2024-06-06 12:45:25,408 - websocket - INFO - Websocket connected
2024-06-06 12:45:25,408 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) connected
2024-06-06 12:45:25,408 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-06-06 12:45:25,411 - api.bybit.ws - INFO - ws subscription - orderbook_stream - category - linear - symbol - ('BTCUSDT', 'linear', 'Bybit')
2024-06-06 12:45:25,411 - api.bybit.ws - INFO - ws subscription - ticker_stream - category - linear - symbol - ('BTCUSDT', 'linear', 'Bybit')
2024-06-06 12:45:25,420 - api.bybit.agent - INFO - Sending get_executions() - category - spot - startTime - 2024-06-05 08:04:40+00:00
2024-06-06 12:45:25,422 - api.bybit.agent - INFO - Sending get_executions() - category - inverse - startTime - 2024-06-05 08:04:40+00:00
2024-06-06 12:45:25,422 - api.bybit.agent - INFO - Sending get_executions() - category - option - startTime - 2024-06-05 08:04:40+00:00
2024-06-06 12:45:25,424 - api.bybit.agent - INFO - Sending get_executions() - category - linear - startTime - 2024-06-05 08:04:40+00:00
2024-06-06 12:45:25,630 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x7ec661cac550>: Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3gd1qo29t7ommtc60-2x4ks'}
2024-06-06 12:45:25,664 - api.bybit.agent - INFO - Sending get_executions() - category - linear - startTime - 2024-06-05 08:04:40+00:00
2024-06-06 12:45:25,849 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x7ec661cac670>: Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3gd1qo29t7ommtc60-2x4ks'}
2024-06-06 12:45:25,850 - websocket - INFO - tearing down on exception Authorization for Unified V5 (Auth) failed. Please check your API keys and resync your system time. Raw error: {'success': False, 'ret_msg': 'Params Error', 'op': 'auth', 'conn_id': 'cno3gd1qo29t7ommtc60-2x4ks'}
2024-06-06 12:45:26,063 - api.bybit.agent - INFO - Bybit - loading trading history, startTime=2024-06-05 08:04:40+00:00, received: 1 records.
2024-06-06 12:45:26,161 - common.init - INFO - Robot EMI=Btc5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,161 - common.init - INFO - Robot EMI=Btc1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,297 - common.init - INFO - Robot EMI=XbtInv1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,297 - common.init - INFO - Robot EMI=Xbt1_1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,298 - common.init - INFO - Robot EMI=Xbt5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,298 - common.init - INFO - Robot EMI=Xbt1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-06 12:45:26,298 - common.init - INFO - Robot EMI=XbtInv5. Adding to 'robots' with STATUS='NOT DEFINED'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/tmatic_240604/main.py", line 16, in refresh
    connect.refresh()
  File "/home/rmn/tmatic_240604/connect.py", line 231, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/home/rmn/tmatic_240604/functions.py", line 761, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/tmatic_240604/functions.py", line 928, in refresh_tables
    if compare != tree.cache[num]:
IndexError: list index out of range
2024-06-06 12:45:31,052 - api.bitmex.ws - INFO - Bitmex - Websocket closed
______Tmatic: Bybit API is still pinging, but the websocket is already closed

**Comment by nikolayromenskiy** [comment]
No such errors in recent days. The issue is closed.
