### ISSUE TITLE
Tmatic stopped after the following error

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#244]
2024-06-12 12:48:22,197 - common.init - INFO - Robot EMI=XbtInv1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-12 12:48:22,200 - common.init - INFO - Robot EMI=Xbt1_1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-12 12:48:22,200 - common.init - INFO - Robot EMI=Xbt1. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-12 12:48:22,201 - common.init - INFO - Robot EMI=Xbt5. Adding to 'robots' with STATUS='NOT DEFINED'
2024-06-12 12:48:22,202 - common.init - INFO - Robot EMI=XbtInv5. Adding to 'robots' with STATUS='NOT DEFINED'
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/tmatic_240611/main.py", line 16, in refresh
    connect.refresh()
  File "/home/rmn/tmatic_240611/connect.py", line 268, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/home/rmn/tmatic_240611/functions.py", line 760, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/tmatic_240611/functions.py", line 927, in refresh_tables
    if compare != tree.cache[num]:
IndexError: list index out of range
______Tmatic: Bybit API is still pinging, but the websocket is already closed

**Comment by evgrmn** [comment]
This error can occur when any TreeTable object has the number of rows configured for that object that does not match the number of rows that the program is attempting to display. Example. You selected Bitmex, where the Account table consisted from 2 rows. Then you select Bybit, but there are 4 rows in the Account table. The TreeTable object must be reconfigured to display 4 rows instead of 2. Otherwise, an error occurs.

Since this issue was published, many improvements have been made and the issue is probably out of date. I think the issue should be closed, otherwise please confirm that the issue is still active.
