### ISSUE TITLE
Error occurred at 20:00 UTC

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#261]
2024-07-25 20:00:00,256 - functions - INFO - Emboldening SQLite
_____________keys {'instrument': ['symbol', 'market'], 'execution': ['execID'], 'orderBook10': ['symbol', 'market'], 'margin': ['currency', 'market'], 'position': ['account', 'symbol', 'market']}
2024-07-25 20:00:01,314 - api.bitmex.ws - ERROR - Traceback (most recent call last):
  File "/home/rmn/tmatic_240725/api/bitmex/ws.py", line 301, in __on_message
    self.transaction(row=val)
  File "/home/rmn/tmatic_240725/functions.py", line 344, in transaction
    Function.funding_display(self, message)
  File "/home/rmn/tmatic_240725/functions.py", line 650, in funding_display
    category=val["CATEGORY"],
KeyError: 'CATEGORY'

_____________keys {'instrument': ['symbol', 'market'], 'execution': ['execID'], 'orderBook10': ['symbol', 'market'], 'margin': ['currency', 'market'], 'position': ['account', 'symbol', 'market']}
2024-07-25 20:00:01,333 - api.bitmex.ws - ERROR - Traceback (most recent call last):
  File "/home/rmn/tmatic_240725/api/bitmex/ws.py", line 301, in __on_message
    self.transaction(row=val)
  File "/home/rmn/tmatic_240725/functions.py", line 344, in transaction
    Function.funding_display(self, message)
  File "/home/rmn/tmatic_240725/functions.py", line 650, in funding_display
    category=val["CATEGORY"],
KeyError: 'CATEGORY'

**Comment by evgrmn** [comment]
This bug was already fixed in some previous commit, probably within an hour of this issue appearing. Hopefully everything works fine now.
