### ISSUE TITLE
Sqlite Error: no such column: None

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#275]
_____query: select MARKET, SYMBOL, sum(QTY) as SUM_QTY from (select abs(QTY) as QTY, MARKET, SYMBOL, SIDE, ACCOUNT from coins where SYMBOL = 'XBTUSD' or SYMBOL = 'XBTUSDT' or SYMBOL = 'SOLUSDT' or SYMBOL = 'ETHUSDT' or SYMBOL = 'ETHUSD') T where SIDE <> 'Fund' and MARKET = 'Bitmex' and ACCOUNT = 296962 group by SYMBOL, MARKET union select MARKET, SYMBOL, sum(QTY) as SUM_QTY from (select abs(QTY) as QTY, MARKET, SYMBOL, SIDE, ACCOUNT from coins where SYMBOL = 'BTCUSDT' or SYMBOL = 'ETHUSDT' or SYMBOL = 'BTCUSD') T where SIDE <> 'Fund' and MARKET = 'Bybit' and ACCOUNT = None group by SYMBOL, MARKET;
2024-08-06 18:08:43,416 - services - ERROR - Sqlite Error: no such column: None)
Exception in thread Thread-1 (setup_market):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/240806/connect.py", line 111, in setup_market
    bots.load_bots()
  File "/home/rmn/240806/bots/init.py", line 459, in load_bots
    for value in data:
TypeError: 'NoneType' object is not iterable

**Comment by evgrmn** [comment]
The program tries to query the database before receiving account data from Bybit (ACCOUNT = None). Fixed in connect.py. The load_bots() function has been moved to another location where the loading of exchanges is fully completed. See commit https://github.com/evgrmn/tmatic/commit/8b0eadc
