### ISSUE TITLE
Error while loading

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#282]
Traceback (most recent call last):
  File "/home/rmn/240817/main.py", line 7, in <module>
    connect.setup()
  File "/home/rmn/240817/connect.py", line 50, in setup
    bot_threads()
  File "/home/rmn/240817/connect.py", line 273, in bot_threads
    functions.activate_bot_thread(bot_name=bot_name)
  File "/home/rmn/240817/functions.py", line 1892, in activate_bot_thread
    timefr_minutes = var.timeframe_human_format[Bots[bot_name].timefr]
KeyError: 1

**Comment by evgrmn** [comment]
Check the 'robots' table in your database, column 'timefr'. The values ​​should be: '1min', '5min', '1h'. Your value is 1, which is not allowed.
