### ISSUE TITLE
AttributeError: 'Instrument' object has no attribute 'volume'

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#290]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\solot\Documents\240822\main.py", line 14, in refresh
    connect.refresh()
  File "C:\Users\solot\Documents\240822\connect.py", line 263, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "C:\Users\solot\Documents\240822\functions.py", line 677, in refresh_on_screen
    Function.refresh_tables(self)
  File "C:\Users\solot\Documents\240822\functions.py", line 957, in refresh_tables
    volume = instrument.volume
             ^^^^^^^^^^^^^^^^^
AttributeError: 'Instrument' object has no attribute 'volume'

**Comment by evgrmn** [comment]
The error probably occurs when there are no trades for a certain instrument yet, so 'volume' has not been initialized. Assigned default value 0. See commit 92ffcd9.
