### ISSUE TITLE
KeyError: 'tickers.BTCUSD'

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#294]
2024-08-22 14:17:56,186 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'spot', 'cursor': 'no'}
2024-08-22 14:17:56,186 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'inverse', 'settleCoin': 'BTC', 'cursor': 'no'}
2024-08-22 14:17:56,194 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'linear', 'settleCoin': 'USDT', 'cursor': 'no'}
2024-08-22 14:17:56,782 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'inverse', 'settleCoin': 'BTC', 'cursor': 'page_args%3D55a116e0-bc85-4a30-870b-1f7f8fa0029a%26'}
2024-08-22 14:17:56,782 - api.bybit.agent - INFO - Sending open_orders() - parameters - {'openOnly': 0, 'limit': 50, 'category': 'linear', 'settleCoin': 'USDT', 'cursor': 'b1347bcd-6bd0-410a-a52b-1fece4f9cda3%3A1724049220100%2C15dde98d-d1a9-4bb7-93eb-27dff32d8e14%3A1724049172832'}
2024-08-22 14:17:57,397 - api.bybit.ws - INFO - Connecting to websocket
2024-08-22 14:17:57,397 - api.bybit.agent - INFO - Sending get_uid_wallet_type()
2024-08-22 14:17:57,403 - api.bybit.agent - INFO - Sending get_wallet_balance() - accountType - UNIFIED
2024-08-22 14:17:57,403 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-08-22 14:17:57,403 - api.bybit.agent - INFO - Sending get_positions() - category - inverse - settlCurrency - BTC
2024-08-22 14:17:57,419 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 attempting connection...
2024-08-22 14:17:57,411 - api.bybit.agent - INFO - Sending get_positions() - category - linear - settlCurrency - USDT
2024-08-22 14:17:57,451 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 (Auth) attempting connection...
2024-08-22 14:17:57,731 - api.bybit.agent - INFO - Sending get_wallet_balance() - accountType - CONTRACT
2024-08-22 14:17:58,576 - api.bybit.agent - INFO - Sending get_positions() - category - linear - settlCurrency - USDT
2024-08-22 14:18:00,530 - websocket - INFO - Websocket connected
2024-08-22 14:18:00,546 - api.bybit.pybit._websocket_stream - INFO - WebSocket Unified V5 connected
2024-08-22 14:18:00,760 - api.bybit.ws - INFO - ws subscription - orderbook_stream - category - inverse - symbol - ('BTCUSD', 'Bybit')
2024-08-22 14:18:01,052 - api.bybit.ws - INFO - ws subscription - ticker_stream - category - inverse - symbol - ('BTCUSD', 'Bybit')
_______________________Unexpected Bybit error: KeyError
Traceback (most recent call last):
  File "C:\Users\solot\Documents\240822_3\api\bybit\errors.py", line 16, in decorator
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\solot\Documents\240822_3\api\bybit\ws.py", line 311, in _on_message
    self.callback(message)
  File "C:\Users\solot\Documents\240822_3\api\bybit\pybit\_websocket_stream.py", line 462, in _handle_incoming_message
    self._process_normal_message(message)
  File "C:\Users\solot\Documents\240822_3\api\bybit\pybit\_websocket_stream.py", line 438, in _process_normal_message
    callback_function = self._get_callback(topic)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\solot\Documents\240822_3\api\bybit\pybit\_websocket_stream.py", line 475, in _get_callback
    return self.callback_directory[topic]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'tickers.BTCUSD'
2024-08-22 14:18:02,307 - api.bybit.errors - ERROR - KeyError - 'tickers.BTCUSD'
2024-08-22 14:18:02,371 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x000001B54A2EB380>: 'WebSocket' object has no attribute 'name'
2024-08-22 14:18:02,749 - websocket - ERROR - error from callback <function _WebSocketManager._connect.<locals>.<lambda> at 0x000001B54C6A5120>: 'WebSocket' object has no attribute 'name'
2024-08-22 14:18:02,797 - websocket - INFO - tearing down on exception 'WebSocket' object has no attribute 'name'
2024-08-22 14:18:03,204 - websocket - INFO - Websocket connected

**Comment by evgrmn** [comment]
This error occurred in the Pybit environment that Tmatic uses. Tmatic uses it as is, without interfering with this software. As I can see from the log, the error occurred when trying to subscribe to ticker_stream, the BTCUSD symbol. The subscription failed for some reason. This error does not actually affect the download process, since presumably the second attempt was fine. This just suggests that perhaps the best way to connect Bybit is to develop own websocket connector instead of using the official one https://github.com/bybit-exchange/pybit.
