### ISSUE TITLE
When I click the Positions tab on the common table the following error occurs

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#299]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 861, in callit
    func(*args)
  File "C:\Users\solot\Documents\240824\main.py", line 14, in refresh
    connect.refresh()
  File "C:\Users\solot\Documents\240824\connect.py", line 263, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "C:\Users\solot\Documents\240824\functions.py", line 706, in refresh_on_screen
    Function.refresh_tables(self)
  File "C:\Users\solot\Documents\240824\functions.py", line 992, in refresh_tables
    sumreal=instrument.sumreal,
            ^^^^^^^^^^^^^^^^^^
AttributeError: 'Instrument' object has no attribute 'sumreal'

**Comment by evgrmn** [comment]
Fixed in commit 77f5903.
