### ISSUE TITLE
8:00 error at Deribit

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#310]
2024-08-30 08:00:01,001 - api.deribit.agent - INFO - Sending private/get_transaction_log - BTC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:01,001 - api.deribit.agent - INFO - Sending private/get_transaction_log - ETH - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:01,002 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:01,002 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDT - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:01,003 - api.deribit.agent - INFO - Sending private/get_transaction_log - EURR - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:01,104 - api.deribit.agent - INFO - Deribit - loading trading history, start_time=2024-08-30 08:00:00+00:00, received: 0 records.
2024-08-30 08:00:05,001 - api.deribit.agent - INFO - Sending private/get_transaction_log - BTC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:05,002 - api.deribit.agent - INFO - Sending private/get_transaction_log - ETH - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:05,002 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:05,005 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDT - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:05,006 - api.deribit.agent - INFO - Sending private/get_transaction_log - EURR - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 08:00:05,106 - api.deribit.agent - INFO - Deribit - loading trading history, start_time=2024-08-30 08:00:00+00:00, received: 2 records.
Exception in thread Thread-14 (funding_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/240829/api/deribit/agent.py", line 850, in funding_thread
    self.transaction(self, row=row, info="History")
TypeError: Function.transaction() got multiple values for argument 'row'

**Comment by evgrmn** [comment]
Fixed in commit 332d8fc.
