### ISSUE TITLE
Error while loading Deribit trading history

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#313]
2024-08-30 14:26:58,874 - api.deribit.ws - INFO - access_token received
2024-08-30 14:26:58,874 - api.deribit.ws - INFO - Connected to websocket.
2024-08-30 14:26:58,875 - api.deribit.ws - INFO - ws subscription - Orderbook - channel - book.ETH-PERPETUAL.none.10.100ms
2024-08-30 14:26:58,875 - api.deribit.ws - INFO - ws subscription - Orderbook - channel - book.BTC-PERPETUAL.none.10.100ms
2024-08-30 14:26:58,875 - api.deribit.ws - INFO - ws subscription - Ticker - channel - ticker.ETH-PERPETUAL.100ms
2024-08-30 14:26:58,876 - api.deribit.ws - INFO - ws subscription - Ticker - channel - ticker.BTC-PERPETUAL.100ms
2024-08-30 14:26:58,876 - api.deribit.ws - INFO - ws subscription - Portfolio - channel - user.portfolio.any
2024-08-30 14:26:58,876 - api.deribit.ws - INFO - ws subscription - User changes - channel - user.changes.any.any.raw
2024-08-30 14:26:58,919 - api.deribit.ws - INFO - Heartbeat established.
2024-08-30 14:26:58,927 - api.deribit.ws - INFO - All subscriptions are successful. Continuing.
2024-08-30 14:26:58,929 - api.deribit.agent - INFO - Sending private/get_transaction_log - BTC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,929 - api.deribit.agent - INFO - Sending private/get_user_trades_by_currency_and_time - BTC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,930 - api.deribit.agent - INFO - Sending private/get_transaction_log - ETH - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,932 - api.deribit.agent - INFO - Sending private/get_user_trades_by_currency_and_time - ETH - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,933 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,934 - api.deribit.agent - INFO - Sending private/get_user_trades_by_currency_and_time - USDC - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,935 - api.deribit.agent - INFO - Sending private/get_transaction_log - USDT - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,936 - api.deribit.agent - INFO - Sending private/get_user_trades_by_currency_and_time - USDT - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,936 - api.deribit.agent - INFO - Sending private/get_transaction_log - EURR - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
2024-08-30 14:26:58,937 - api.deribit.agent - INFO - Sending private/get_user_trades_by_currency_and_time - EURR - period - 2024-08-30 08:00:00+00:00 - 2024-12-08 08:00:00+00:00
Exception in thread Thread-121 (get_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/240830/api/deribit/agent.py", line 439, in get_in_thread
    if res["execType"] == "Funding":
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-123 (get_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/240830/api/deribit/agent.py", line 439, in get_in_thread
    if res["execType"] == "Funding":
TypeError: list indices must be integers or slices, not str
Exception in thread Thread-127 (get_in_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/240830/api/deribit/agent.py", line 439, in get_in_thread
    if res["execType"] == "Funding":
TypeError: list indices must be integers or slices, not str
2024-08-30 14:26:59,041 - connect - ERROR - Deribit: The trade history is not loaded.

**Comment by evgrmn** [comment]
Fixed in commit 483700c.
