### ISSUE TITLE
The latest version successfully created .env.Settings file but does not load

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#319]
2024-09-09 18:08:11,443 - root - INFO - 

hello

2024-09-09 18:08:11,985 - api.api - INFO - Bitmex - Requesting all active instruments.
2024-09-09 18:08:11,986 - api.api - INFO - Bybit - Requesting all active instruments.
2024-09-09 18:08:11,987 - api.api - INFO - Deribit - Requesting all active instruments.
2024-09-09 18:08:12,422 - api.errors - ERROR - On request GET /instrument/active - error - Bitmex - HTTPError - 401 Unauthorized - Bitmex loading cancelled.
2024-09-09 18:08:12,422 - api.bitmex.agent - ERROR - A list was expected when loading instruments, but was not received. Reboot
2024-09-09 18:08:12,555 - api.api - INFO - Deribit - Requesting open orders.
2024-09-09 18:08:12,599 - api.errors - WARNING - On request POST /api/v2/private/get_open_orders - error - Deribit - HTTPError - Unexpected HTTPError b'{"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":true,"usIn":1725905293600097,"usOut":1725905293600350,"usDiff":253}'
2024-09-09 18:08:12,599 - api.deribit.agent - ERROR - Invalid data was received when loading instruments. IGNORE
2024-09-09 18:08:13,288 - api.api - INFO - Bybit - Requesting open orders.
2024-09-09 18:08:13,839 - api.errors - ERROR - On request GET get_open_orders - error - Bybit - FailedRequestError - 401 Invalid request. 1. Need to use the correct key to access; 2. Need to put authentication params in the request header - Bybit loading cancelled.
2024-09-09 18:08:13,839 - api.bybit.ws - INFO - Bybit - Websocket closed
2024-09-09 18:08:14,601 - connect - INFO - 

2024-09-09 18:08:14,602 - connect - INFO - Something went wrong while loading Deribit. Reboot.

2024-09-09 18:08:17,605 - api.api - INFO - Deribit - Requesting all active instruments.
2024-09-09 18:08:17,797 - api.api - INFO - Deribit - Requesting open orders.
2024-09-09 18:08:17,841 - api.errors - WARNING - On request POST /api/v2/private/get_open_orders - error - Deribit - HTTPError - Unexpected HTTPError b'{"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":true,"usIn":1725905298842541,"usOut":1725905298842874,"usDiff":333}'
2024-09-09 18:08:17,842 - api.deribit.agent - ERROR - Invalid data was received when loading instruments. IGNORE
2024-09-09 18:08:19,844 - connect - INFO - 

2024-09-09 18:08:19,844 - connect - INFO - Something went wrong while loading Deribit. Reboot.

2024-09-09 18:08:22,847 - api.api - INFO - Deribit - Requesting all active instruments.
2024-09-09 18:08:23,016 - api.api - INFO - Deribit - Requesting open orders.
2024-09-09 18:08:23,061 - api.errors - WARNING - On request POST /api/v2/private/get_open_orders - error - Deribit - HTTPError - Unexpected HTTPError b'{"jsonrpc":"2.0","error":{"message":"invalid_credentials","code":13004},"testnet":true,"usIn":1725905304062294,"usOut":1725905304062534,"usDiff":240}'
2024-09-09 18:08:23,061 - api.deribit.agent - ERROR - Invalid data was received when loading instruments. IGNORE
2024-09-09 18:08:25,064 - connect - INFO -

**Comment by evgrmn** [comment]
Fixed in commit b14dd1b.

**Comment by evgrmn** [comment]
See commit 953b9ac.

**Comment by nikolayromenskiy** [comment]
The new error below:

2024-09-10 05:51:13,267 - api.api - INFO - Bybit - Requesting all active instruments.
2024-09-10 05:51:13,267 - api.api - INFO - Bitmex - Requesting all active instruments.
2024-09-10 05:51:13,270 - api.api - INFO - Deribit - Requesting all active instruments.
2024-09-10 05:51:13,615 - api.api - INFO - Bitmex - Requesting open orders.
2024-09-10 05:51:13,743 - api.bitmex.ws - INFO - Connecting to websocket
2024-09-10 05:51:13,748 - api.bitmex.ws - INFO - Authenticating with API key.
2024-09-10 05:51:13,756 - api.api - INFO - Bitmex - Requesting user information.
2024-09-10 05:51:13,758 - api.api - INFO - Bitmex - Requesting account.
2024-09-10 05:51:13,764 - api.api - INFO - Deribit - Requesting open orders.
2024-09-10 05:51:13,783 - api.api - INFO - Bitmex - Requesting positions.
2024-09-10 05:51:13,832 - api.errors - ERROR - On request POST /api/v2/private/get_open_orders - error - Deribit - HTTPError - 13004 invalid_credentials - Deribit loading cancelled.
2024-09-10 05:51:13,832 - api.deribit.agent - ERROR - Invalid data was received when loading instruments. CANCEL
2024-09-10 05:51:14,175 - websocket - INFO - Websocket connected
2024-09-10 05:51:14,257 - api.bitmex.ws - INFO - ws subscribe - ['position:XBTUSDT', 'instrument:XBTUSDT', 'margin:XBTUSDT', 'execution:XBTUSDT', 'orderBook10:XBTUSDT']
2024-09-10 05:51:14,258 - api.bitmex.ws - INFO - ws subscribe - ['position:XBTUSD', 'instrument:XBTUSD', 'margin:XBTUSD', 'execution:XBTUSD', 'orderBook10:XBTUSD']
2024-09-10 05:51:14,258 - api.bitmex.ws - INFO - Connected to websocket.
2024-09-10 05:51:14,463 - api.bitmex.ws - INFO - Data received. Continuing.
2024-09-10 05:51:14,465 - api.api - INFO - Bitmex - Requesting trading history - start_time=2024-09-08 12:00:00+00:00
2024-09-10 05:51:14,641 - api.api - INFO - Bybit - Requesting open orders.
2024-09-10 05:51:14,837 - api.errors - ERROR - On request GET get_open_orders - error - Bybit - FailedRequestError - 401 Invalid request. 1. Need to use the correct key to access; 2. Need to put authentication params in the request header - Bybit loading cancelled.
2024-09-10 05:51:14,837 - api.bybit.ws - INFO - Bybit - Websocket closed
2024-09-10 05:51:15,056 - botinit.init - INFO - Added subscription to ('ETHUSD', 'Bitmex').
2024-09-10 05:51:15,057 - botinit.init - INFO - Added subscription to ('ETHUSDT', 'Bitmex').
2024-09-10 05:51:15,057 - api.bitmex.ws - INFO - ws subscribe - ['position:ETHUSD', 'instrument:ETHUSD', 'margin:ETHUSD', 'execution:ETHUSD', 'orderBook10:ETHUSD']
2024-09-10 05:51:15,259 - api.bitmex.ws - INFO - ws subscribe - ['position:ETHUSDT', 'instrument:ETHUSDT', 'margin:ETHUSDT', 'execution:ETHUSDT', 'orderBook10:ETHUSDT']
2024-09-10 05:51:15,428 - api.api - INFO - Bitmex - Requesting kline data - symbol=XBTUSDT, start_time=2024-09-10 05:32:00+00:00, timeframe=1
2024-09-10 05:51:15,530 - api.api - INFO - Bitmex - Klines - symbol=XBTUSDT, start_time=2024-09-10 05:32:00+00:00, timeframe=1, received 20 records.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/240909/main.py", line 14, in refresh
    connect.refresh()
  File "/home/rmn/240909/connect.py", line 293, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/home/rmn/240909/functions.py", line 776, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/240909/functions.py", line 802, in refresh_tables
    if compare != tree.cache[num]:
KeyError: 1

**Comment by nikolayromenskiy** [comment]
No such an error this time. Closed.
