### ISSUE TITLE
Settings menu: Bitmex, Deribit. Then I change order to Deribit, Bitmex, and then <F3>. The error occurs.

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#333]
2024-09-12 05:28:34,598 - api.bitmex.ws - INFO - Bitmex - Websocket closed
2024-09-12 05:28:34,619 - api.deribit.ws - INFO - Websocket closed.
2024-09-12 05:28:34,682 - api.api - INFO - Deribit - Requesting all active instruments.
2024-09-12 05:28:34,683 - api.api - INFO - Bitmex - Requesting all active instruments.
2024-09-12 05:28:34,950 - api.api - INFO - Bitmex - Requesting open orders.
2024-09-12 05:28:34,951 - api.api - INFO - Deribit - Requesting open orders.
2024-09-12 05:28:35,004 - api.deribit.ws - INFO - Connecting to websocket
2024-09-12 05:28:35,005 - api.api - INFO - Deribit - Requesting user information.
2024-09-12 05:28:35,006 - api.api - INFO - Deribit - Requesting account.
2024-09-12 05:28:35,010 - api.api - INFO - Deribit - Requesting positions.
2024-09-12 05:28:35,022 - api.bitmex.ws - INFO - Connecting to websocket
2024-09-12 05:28:35,022 - api.api - INFO - Bitmex - Requesting user information.
2024-09-12 05:28:35,023 - api.api - INFO - Bitmex - Requesting account.
2024-09-12 05:28:35,023 - api.api - INFO - Bitmex - Requesting positions.
2024-09-12 05:28:35,023 - api.bitmex.ws - INFO - Authenticating with API key.
2024-09-12 05:28:35,150 - websocket - INFO - Websocket connected
2024-09-12 05:28:35,211 - api.deribit.ws - INFO - access_token received
2024-09-12 05:28:35,211 - api.deribit.ws - INFO - Connected to websocket.
2024-09-12 05:28:35,212 - api.deribit.ws - INFO - ws subscription - Orderbook - channel - book.BTC-PERPETUAL.none.10.100ms
2024-09-12 05:28:35,213 - api.deribit.ws - INFO - ws subscription - Ticker - channel - ticker.BTC-PERPETUAL.100ms
2024-09-12 05:28:35,213 - api.deribit.ws - INFO - ws subscription - Portfolio - channel - user.portfolio.any
2024-09-12 05:28:35,214 - api.deribit.ws - INFO - ws subscription - User changes - channel - user.changes.any.any.raw
2024-09-12 05:28:35,254 - api.deribit.ws - INFO - Heartbeat established.
2024-09-12 05:28:35,261 - websocket - INFO - Websocket connected
2024-09-12 05:28:35,266 - api.deribit.ws - INFO - All subscriptions are successful. Continuing.
2024-09-12 05:28:35,268 - api.api - INFO - Deribit - Requesting trading history - start_time=2024-09-11 08:00:00+00:00
2024-09-12 05:28:35,328 - api.bitmex.ws - INFO - ws subscribe - ['margin:XBTUSDT', 'orderBook10:XBTUSDT', 'instrument:XBTUSDT', 'position:XBTUSDT', 'execution:XBTUSDT']
2024-09-12 05:28:35,329 - api.bitmex.ws - INFO - ws subscribe - ['margin:XBTUSD', 'orderBook10:XBTUSD', 'instrument:XBTUSD', 'position:XBTUSD', 'execution:XBTUSD']
2024-09-12 05:28:35,329 - api.bitmex.ws - INFO - Connected to websocket.
2024-09-12 05:28:35,441 - api.bitmex.ws - INFO - Data received. Continuing.
2024-09-12 05:28:35,442 - api.api - INFO - Bitmex - Requesting trading history - start_time=2024-09-12 04:00:00+00:00
2024-09-12 05:28:35,443 - api.api - INFO - Bitmex - Requesting kline data - symbol=XBTUSDT, start_time=2024-09-12 05:09:00+00:00, timeframe=1
2024-09-12 05:28:35,531 - api.api - INFO - Bitmex - Klines - symbol=XBTUSDT, start_time=2024-09-12 05:09:00+00:00, timeframe=1, received 21 records.
2024-09-12 05:28:35,658 - botinit.init - INFO - Added subscription to ('BTC_USDT-PERPETUAL', 'Deribit').
2024-09-12 05:28:35,658 - botinit.init - INFO - Added subscription to ('ETH-PERPETUAL', 'Deribit').
2024-09-12 05:28:35,658 - botinit.init - INFO - Added subscription to ('ETHUSD', 'Bitmex').
2024-09-12 05:28:35,658 - botinit.init - INFO - Added subscription to ('ETHUSDT', 'Bitmex').
2024-09-12 05:28:35,659 - api.deribit.ws - INFO - ws subscription - Orderbook - channel - ['book.BTC_USDT-PERPETUAL.none.10.100ms']
2024-09-12 05:28:35,659 - api.deribit.ws - INFO - ws subscription - Ticker - channel - ['ticker.BTC_USDT-PERPETUAL.100ms']
2024-09-12 05:28:35,709 - api.deribit.ws - INFO - All subscriptions are successful. Continuing.
2024-09-12 05:28:35,710 - api.deribit.ws - INFO - ws subscription - Orderbook - channel - ['book.ETH-PERPETUAL.none.10.100ms']
2024-09-12 05:28:35,710 - api.deribit.ws - INFO - ws subscription - Ticker - channel - ['ticker.ETH-PERPETUAL.100ms']
2024-09-12 05:28:35,761 - api.deribit.ws - INFO - All subscriptions are successful. Continuing.
2024-09-12 05:28:35,762 - api.bitmex.ws - INFO - ws subscribe - ['margin:ETHUSD', 'orderBook10:ETHUSD', 'instrument:ETHUSD', 'position:ETHUSD', 'execution:ETHUSD']
2024-09-12 05:28:35,863 - api.bitmex.ws - INFO - ws subscribe - ['margin:ETHUSDT', 'orderBook10:ETHUSDT', 'instrument:ETHUSDT', 'position:ETHUSDT', 'execution:ETHUSDT']
2024-09-12 05:28:35,981 - display.bot_menu - WARNING - There was an error loading algo.test_bot.strategy:

The instrument ('BTCUSDT', 'Bybit') not found.

Correct the strategy file or delete ``test_bot`` using the ``Bot Menu``.

2024-09-12 05:28:36,014 - api.api - INFO - Bitmex - Requesting kline data - symbol=XBTUSDT, start_time=2024-09-12 05:09:00+00:00, timeframe=1
2024-09-12 05:28:36,458 - api.api - INFO - Bitmex - Klines - symbol=XBTUSDT, start_time=2024-09-12 05:09:00+00:00, timeframe=1, received 21 records.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/240911/main.py", line 14, in refresh
    connect.refresh()
  File "/home/rmn/240911/connect.py", line 295, in refresh
    Function.refresh_on_screen(Markets[var.current_market], utc=utc)
  File "/home/rmn/240911/functions.py", line 776, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/240911/functions.py", line 906, in refresh_tables
    val=instrument.bids,
AttributeError: 'Instrument' object has no attribute 'bids'

**Comment by nikolayromenskiy** [comment]
I do not see problems after last commits.
