### ISSUE TITLE
The ghost row in the instrument's table leads to the error below

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#344]
![Screenshot from 2024-09-20 21-09-47](https://github.com/user-attachments/assets/af0da2c8-c0ca-4c7b-9821-03d17a65356c)

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/240920_1/functions.py", line 1939, in handler_instrument
    if var.symbol != ws.symbol_list[row_position]:
IndexError: list index out of range

**Comment by nikolayromenskiy** [comment]
The new hierarchical display of the instruments' table solved the problem. Issue closed.
