### ISSUE TITLE
Error after I unsubscribe from a symbol and the next symbol is option

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#363]
I subscribed to ETH_USDC-25OCT24_series, and then to ALGO_USDC-PERPETUAL. Then I unsubscribed from ALGO_USDC-PERPETUAL and got the error below. At the same time the Option Desk was displayed which shouldn't have been. 

2024-10-04 15:42:22,243 - functions - INFO - Deribit - Added subscription to ETH_USDC-25OCT24_series.
2024-10-04 15:42:40,683 - functions - INFO - Deribit - Subscription to ALGO_USDC-PERPETUAL. Waiting for confirmation from Deribit.
2024-10-04 15:42:40,684 - api.deribit.ws - INFO - Deribit - ws subscription - Orderbook - channel - ['book.ALGO_USDC-PERPETUAL.none.10.100ms']
2024-10-04 15:42:40,687 - api.deribit.ws - INFO - Deribit - ws subscription - Ticker - channel - ['ticker.ALGO_USDC-PERPETUAL.100ms']
2024-10-04 15:42:40,738 - functions - INFO - Deribit - Added subscription to ALGO_USDC-PERPETUAL.
2024-10-04 15:42:46,718 - functions - INFO - Deribit - Unsubscribe from ALGO_USDC-PERPETUAL. Waiting for confirmation from Deribit.
2024-10-04 15:42:46,718 - api.deribit.ws - INFO - Deribit - ws unsubscribe - Orderbook, Ticker - channel - ['book.ALGO_USDC-PERPETUAL.none.10.100ms', 'ticker.ALGO_USDC-PERPETUAL.100ms']
2024-10-04 15:42:46,769 - functions - INFO - Deribit - Unsubscribed from ALGO_USDC-PERPETUAL.
Exception in thread Thread-46 (confirm_unsubscribe):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/241004/functions.py", line 2284, in confirm_unsubscribe
    update_order_form()
  File "/home/rmn/241004/functions.py", line 1819, in update_order_form
    Function.volume(ws, qty=instrument.minOrderQty, symbol=var.symbol),
AttributeError: 'Instrument' object has no attribute 'minOrderQty'

**Comment by evgrmn** [comment]
Fixed in commit 7eb9456.
