### ISSUE TITLE
Subscription to option_combo on Deribit

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#364]
The option strategies on Deribit probably have no its Opion Desk. That's why Tmatic gives the following error trying to display the Option Desk.

2024-10-04 16:00:05,599 - functions - INFO - Deribit - Subscription to BTC-CSR12-28MAR25_series. Waiting for confirmation from Deribit.
2024-10-04 16:00:05,599 - api.deribit.ws - INFO - Deribit - ws subscription - Orderbook - channel - ['book.BTC-CSR12-28MAR25-64000_65000.none.10.100ms', 'book.BTC-CSR12-28MAR25-65000_66000.none.10.100ms']
2024-10-04 16:00:05,602 - api.deribit.ws - INFO - Deribit - ws subscription - Ticker - channel - ['ticker.BTC-CSR12-28MAR25-64000_65000.100ms', 'ticker.BTC-CSR12-28MAR25-65000_66000.100ms']
2024-10-04 16:00:05,652 - functions - INFO - Deribit - Added subscription to BTC-CSR12-28MAR25_series.
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/rmn/241004/functions.py", line 2168, in handler_instrument
    options_desk.create(instrument=instrument, update=update_order_form)
  File "/home/rmn/241004/display/option_desk.py", line 205, in create
    indx = self.puts_list.index(option)
ValueError: 'BTC-CSR12-28MAR25-64000_65000' is not in list

**Comment by nikolayromenskiy** [comment]
Fixed in one of recent commits.
