### ISSUE TITLE
Error trying to unsubscribe from Bybit option

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#371]
KeyError: ('BTC-26SEP25_series', 'Bybit')
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/rmn/241009/functions.py", line 2049, in handler_instrument
    options_desk.create(
  File "/home/rmn/241009/display/option_desk.py", line 198, in create
    option = var.selected_option[(self.symbol, self.market)][0]
KeyError: ('BTC-26SEP25_series', 'Bybit')

**Comment by evgrmn** [comment]
I can't see this error when unsubscribing at the moment. Maybe the error was fixed in one of the previous commits.
