### ISSUE TITLE
An error in the end of Tmatic loading

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#376]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/241011/main.py", line 14, in refresh
    connect.refresh()
  File "/home/rmn/241011/connect.py", line 311, in refresh
    Function.refresh_on_screen(ws, utc=utc)
  File "/home/rmn/241011/functions.py", line 783, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/241011/functions.py", line 1170, in refresh_tables
    display_order_book_values(
  File "/home/rmn/241011/functions.py", line 1105, in display_order_book_values
    if compare != tree.cache[number]:
KeyError: 14

**Comment by evgrmn** [comment]
Fixed in commit fe680db.
