### ISSUE TITLE
Error when no market connected

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#377]
2024-10-11 15:57:52,517 - root - INFO - 

hello

2024-10-11 15:57:53,078 - botinit.init - WARNING -  - test_bot_3 bot has open position on ('XBTUSD', 'Bitmex'), but Bitmex is not enabled. Position on ('XBTUSD', 'Bitmex') ignored. Add Bitmex to the .env.Settings file.
2024-10-11 15:57:53,079 - botinit.init - WARNING -  - test_bot_3 bot has open position on ('XBTUSDT', 'Bitmex'), but Bitmex is not enabled. Position on ('XBTUSDT', 'Bitmex') ignored. Add Bitmex to the .env.Settings file.
2024-10-11 15:57:53,113 - display.bot_menu - WARNING - There was an error loading algo.test_bot.strategy:

The instrument ('BTCUSDT', 'Bybit') not found.

Correct the strategy file or delete ``test_bot`` using the ``Bot Menu``.

2024-10-11 15:57:53,122 - display.bot_menu - WARNING - There was an error loading algo.test_bot_3.strategy:

The instrument ('XBTUSDT', 'Bitmex') not found.

Correct the strategy file or delete ``test_bot_3`` using the ``Bot Menu``.

Traceback (most recent call last):
  File "/home/rmn/241011/main.py", line 7, in <module>
    connect.setup()
  File "/home/rmn/241011/connect.py", line 87, in setup
    functions.update_order_form()
  File "/home/rmn/241011/functions.py", line 1900, in update_order_form
    if instrument.ticker == "option!":
AttributeError: 'Instrument' object has no attribute 'ticker'

**Comment by evgrmn** [comment]
Fixed in commit b864160.
