### ISSUE TITLE
Start Tmatic, then go to Settings page, then uncheck all markets and 'Reload all'. The following error occurres.

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#378]
2024-10-11 17:39:50,421 - api.bitmex.ws - INFO - Bitmex - Websocket closed
2024-10-11 17:39:51,381 - api.bybit.ws - INFO - Bybit - Websocket closed
2024-10-11 17:39:51,428 - api.deribit.ws - INFO - Websocket closed.
2024-10-11 17:39:51,456 - botinit.init - WARNING -  - test_bot_3 bot has open position on ('XBTUSD', 'Bitmex'), but Bitmex is not enabled. Position on ('XBTUSD', 'Bitmex') ignored. Add Bitmex to the .env.Settings file.
2024-10-11 17:39:51,457 - botinit.init - WARNING -  - test_bot_3 bot has open position on ('XBTUSDT', 'Bitmex'), but Bitmex is not enabled. Position on ('XBTUSDT', 'Bitmex') ignored. Add Bitmex to the .env.Settings file.
Exception in thread Thread-112 (terminal_reload_thread):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rmn/241011/connect.py", line 335, in terminal_reload_thread
    setup()
  File "/home/rmn/241011/connect.py", line 73, in setup
    bot_manager.create_bots_menu()
  File "/home/rmn/241011/display/bot_menu.py", line 256, in create_bots_menu
    self.insert_bot_menu(name)
  File "/home/rmn/241011/display/bot_menu.py", line 241, in insert_bot_menu
    tree.insert_hierarchical(
  File "/home/rmn/241011/display/variables.py", line 1064, in insert_hierarchical
    self.tree.insert(
  File "/usr/lib/python3.10/tkinter/ttk.py", line 1361, in insert
    res = self.tk.call(self._w, "insert", parent, index,
_tkinter.TclError: Item test_bot already exists

**Comment by evgrmn** [comment]
Fixed in commit 386fb02.
