### ISSUE TITLE
Error after the Option Desk popped up, and a strike (call or put) selected

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#382]
No error if the Option Desk never popped up.
No error if the Option Desk popped up and then closed.
But if I pop the Option Desk up, select a strike (call or put), and after that try to scroll above absolutely any widget by the mouse scroll wheel, then the following error occurs:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/rmn/241012/display/variables.py", line 45, in <lambda>
    lambda event: on_canvas_mousewheel(event, canvas, scroll, ostype),
  File "/home/rmn/241012/display/variables.py", line 67, in on_canvas_mousewheel
    slider_position = scroll.get()
  File "/usr/lib/python3.10/tkinter/__init__.py", line 3564, in get
    return self._getdoubles(self.tk.call(self._w, 'get'))
_tkinter.TclError: invalid command name ".!toplevel2.!frame.!frame4.!autoscrollbar"

**Comment by evgrmn** [comment]
Fixed in commit c58cb21.
