### ISSUE TITLE
Tmatic does not start after KeyError: 'Bybit'

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#390]
2024-12-15 18:23:10,503 - root - INFO -

hello

2024-12-15 18:23:10,934 - api.api - INFO - Bitmex - Requesting all active instruments.
2024-12-15 18:23:10,934 - api.bitmex.ws - INFO - Connecting to websocket
2024-12-15 18:23:10,934 - api.bitmex.ws - INFO - Authenticating with API key.
2024-12-15 18:23:11,288 - websocket - INFO - Websocket connected
2024-12-15 18:23:11,360 - api.bitmex.ws - INFO - Connected to websocket.
2024-12-15 18:23:11,717 - api.api - INFO - Bitmex - Requesting open orders.
2024-12-15 18:23:11,803 - api.bitmex.ws - INFO - ws subscribe - ['margin:XBTZ24', 'instrument:XBTZ24', 'position:XBTZ24', 'execution:XBTZ24', 'orderBook10:XBTZ24']
2024-12-15 18:23:11,803 - api.bitmex.ws - INFO - ws subscribe - ['margin:XBTUSDT', 'instrument:XBTUSDT', 'position:XBTUSDT', 'execution:XBTUSDT', 'orderBook10:XBTUSDT']
2024-12-15 18:23:11,803 - api.api - INFO - Bitmex - Requesting user information.
2024-12-15 18:23:11,803 - api.api - INFO - Bitmex - Requesting account.
2024-12-15 18:23:11,812 - api.api - INFO - Bitmex - Requesting positions.
2024-12-15 18:23:11,915 - api.bitmex.ws - INFO - Data received. Continuing.
2024-12-15 18:23:12,398 - api.api - INFO - Bitmex - Request for trading history since 2024-12-15 12:00:00+00:00
2024-12-15 18:23:12,493 - api.api - INFO - Bitmex - From the trading history received: 5 records
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to XBTUSD.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to XBTUSD.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to XBTUSD.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to SOLUSDT.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to ETHUSDT.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to ETHUSDT.
2024-12-15 18:23:12,538 - botinit.init - INFO - Added subscription to ETHUSD.
2024-12-15 18:23:12,538 - functions - INFO - Bitmex - Subscription to XBTUSD. Waiting for confirmation from Bitmex.
2024-12-15 18:23:12,546 - api.bitmex.ws - INFO - ws subscribe - ['margin:XBTUSD', 'instrument:XBTUSD', 'position:XBTUSD', 'execution:XBTUSD', 'orderBook10:XBTUSD']
2024-12-15 18:23:12,546 - functions - INFO - Bitmex - Subscription to SOLUSDT. Waiting for confirmation from Bitmex.
2024-12-15 18:23:12,546 - api.bitmex.ws - INFO - ws subscribe - ['margin:SOLUSDT', 'instrument:SOLUSDT', 'position:SOLUSDT', 'execution:SOLUSDT', 'orderBook10:SOLUSDT']
2024-12-15 18:23:12,546 - functions - INFO - Bitmex - Subscription to ETHUSD. Waiting for confirmation from Bitmex.
2024-12-15 18:23:12,546 - functions - INFO - Bitmex - Subscription to ETHUSDT. Waiting for confirmation from Bitmex.
2024-12-15 18:23:12,546 - api.bitmex.ws - INFO - ws subscribe - ['margin:ETHUSD', 'instrument:ETHUSD', 'position:ETHUSD', 'execution:ETHUSD', 'orderBook10:ETHUSD']
2024-12-15 18:23:12,546 - api.bitmex.ws - INFO - ws subscribe - ['margin:ETHUSDT', 'instrument:ETHUSDT', 'position:ETHUSDT', 'execution:ETHUSDT', 'orderBook10:ETHUSDT']
Traceback (most recent call last):
  File "C:\Users\solot\Documents\241215\main.py", line 6, in <module>
    connect.setup()
  File "C:\Users\solot\Documents\241215\connect.py", line 60, in setup
    botinit.load_bots()
  File "C:\Users\solot\Documents\241215\botinit\init.py", line 263, in load_bots
    instrument = ws.Instrument[symbol]
                 ~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\solot\Documents\241215\common\data.py", line 229, in __getitem__
    return self.market[name][item]
           ~~~~~~~~~~~^^^^^^
KeyError: 'Bybit'
2024-12-15 18:23:12,652 - functions - INFO - Bitmex - Added subscription to SOLUSDT.
2024-12-15 18:23:12,652 - functions - INFO - Bitmex - Added subscription to XBTUSD.
2024-12-15 18:23:12,753 - functions - INFO - Bitmex - Added subscription to ETHUSDT.
2024-12-15 18:23:12,753 - functions - INFO - Bitmex - Added subscription to ETHUSD.
Exception in thread Thread-1 (kline_update):
Traceback (most recent call last):
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\solot\Documents\241215\functions.py", line 2628, in kline_update
    t.start()
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

**Comment by evgrmn** [comment]
Fixed in commit c291db3.
