### ISSUE TITLE
Some error occurred. BTC-PERPETUAL is not in the subscription list

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#408]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 839, in callit
    func(*args)
  File "/home/rmn/241229/main.py", line 13, in refresh
    connect.refresh()
  File "/home/rmn/241229/connect.py", line 329, in refresh
    Function.refresh_on_screen(ws, utc=utc)
  File "/home/rmn/241229/functions.py", line 846, in refresh_on_screen
    Function.refresh_tables(self)
  File "/home/rmn/241229/functions.py", line 1305, in refresh_tables
    Function.display_positions(self)
  File "/home/rmn/241229/functions.py", line 1026, in display_positions
    instrument = ws.Instrument[symbol]
  File "/home/rmn/241229/common/data.py", line 229, in __getitem__
    return self.market[name][item]
KeyError: ('BTC-PERPETUAL', 'Deribit')

**Comment by evgrmn** [comment]
Fixed in commit d3cdaaf.
